name: Seed Habitica Daily Task (Pacific -> +OFFSET_DAYS)

# Runs daily at 15:05 UTC (which is 08:05 PDT while DST is active).
# NOTE: During PST (after DST ends) 15:05 UTC = 07:05 PST. If you want a constant 08:05 local time
# you must change the cron to 16:05 UTC after DST ends (or use a scheduler outside GitHub Actions).
on:
  schedule:
    - cron: '5 15 * * *'     # daily at 15:05 UTC
  workflow_dispatch:         # manual run button in Actions tab

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      HABITICA_USER_ID: ${{ secrets.HABITICA_USER_ID }}
      HABITICA_API_TOKEN: ${{ secrets.HABITICA_API_TOKEN }}
      QUOTES_SOURCE: repo
      OFFSET_DAYS: '30'     # create task 30 days from "today in Pacific time"
      DEBUG: 'false'        # set to 'true' while testing
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run Habitica seeder
        run: python habitica_seed.py
