name: Seed Habitica Daily Tasks

on:
  schedule:
    - cron: '0 2 * * 1'   # weekly; change if you want
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      HABITICA_USER_ID: ${{ secrets.HABITICA_USER_ID }}
      HABITICA_API_TOKEN: ${{ secrets.HABITICA_API_TOKEN }}
      # ====== your new config values ======
      QUOTES_SOURCE: repo   # or "" for local quotes
      DAYS_AHEAD: '1'           # use '1' to test; change to '7' or '14' later
      DEBUG: 'true'             # optional — keeps debug prints in logs
      # =====================================
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run Habitica seeder
        run: python habitica_seed.py
